spring:
  profiles.active: dev,native
  cloud.config.server.native.searchLocations: file:/var/allure-service/config

server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'